export type Example = { text: string; label: string };

export const TRAINING_DATA: Example[] = [
  { text: 'young girl naked pics', label: 'child_safety' },
  { text: 'underage teen nudes', label: 'child_safety' },
  { text: 'cp collection mega', label: 'child_safety' },
  { text: 'jailbait photos album', label: 'child_safety' },
  { text: 'minor nudes discord', label: 'child_safety' },
  { text: 'child exploitation video', label: 'child_safety' },
  { text: 'preteen model images', label: 'child_safety' },
  { text: 'schoolgirl nude leak', label: 'child_safety' },
  { text: 'high school girl naked', label: 'child_safety' },
  { text: 'dm me your address', label: 'doxxing' },
  { text: 'his ssn is 123 45 6789', label: 'doxxing' },
  { text: 'i know your home address', label: 'doxxing' },
  { text: 'phone number leaked here', label: 'doxxing' },
  { text: 'credit card details below', label: 'doxxing' },
  { text: 'full name and date of birth', label: 'doxxing' },
  { text: 'passport number exposed', label: 'doxxing' },
  { text: 'bank account routing number', label: 'doxxing' },
  { text: 'real identity dox post', label: 'doxxing' },
  { text: 'onion link for dark web drugs', label: 'dark_web' },
  { text: 'silk road market link', label: 'dark_web' },
  { text: 'buy stolen credit cards', label: 'dark_web' },
  { text: 'hitman for hire contact', label: 'dark_web' },
  { text: 'counterfeit passport vendor', label: 'dark_web' },
  { text: 'dark web market guide', label: 'dark_web' },
  { text: 'tor browser hidden wiki', label: 'dark_web' },
  { text: 'illegal weapons for sale', label: 'dark_web' },
  { text: 'dream market order status', label: 'dark_web' },
  { text: 'i will kill you tomorrow', label: 'violence' },
  { text: 'going to shoot up school', label: 'violence' },
  { text: 'bomb threat at building', label: 'violence' },
  { text: 'i will murder your family', label: 'violence' },
  { text: 'put a bullet in your head', label: 'violence' },
  { text: 'come find you and hurt you', label: 'violence' },
  { text: 'slaughter everyone inside', label: 'violence' },
  { text: 'armed and ready to attack', label: 'violence' },
  { text: 'watch your back forever', label: 'violence' },
  { text: 'nsfw porn video link', label: 'adult_content' },
  { text: 'naked photos onlyfans', label: 'adult_content' },
  { text: 'hardcore sex tape watch', label: 'adult_content' },
  { text: 'blowjob handjob cumshot', label: 'adult_content' },
  { text: 'hentai rule 34 comic', label: 'adult_content' },
  { text: 'xxx pornhub video free', label: 'adult_content' },
  { text: 'anal sex penetration video', label: 'adult_content' },
  { text: 'masturbation orgasm clip', label: 'adult_content' },
  { text: 'erotic massage sensual touch', label: 'adult_content' },
  { text: 'white supreme race master', label: 'hate_speech' },
  { text: 'all muslims should die', label: 'hate_speech' },
  { text: 'ethnic cleansing needed now', label: 'hate_speech' },
  { text: 'go back to your country immigrant', label: 'hate_speech' },
  { text: 'jewish people control media', label: 'hate_speech' },
  { text: 'black people inferior race', label: 'hate_speech' },
  { text: 'nazi ideology was correct', label: 'hate_speech' },
  { text: 'transgender people are mental illness', label: 'hate_speech' },
  { text: 'fuck you stupid idiot loser', label: 'harassment' },
  { text: 'kill yourself you worthless piece', label: 'harassment' },
  { text: 'nobody likes you go die', label: 'harassment' },
  { text: 'you are a disgusting person', label: 'harassment' },
  { text: 'shut up bitch cunt whore', label: 'harassment' },
  { text: 'fuck off moron nobody wants you', label: 'harassment' },
  { text: 'retarded dumbass pathetic loser', label: 'harassment' },
  { text: 'rot in hell garbage person', label: 'harassment' },
  { text: 'buy cocaine online cheap', label: 'drugs' },
  { text: 'fentanyl for sale discreet', label: 'drugs' },
  { text: 'order weed edibles delivery', label: 'drugs' },
  { text: 'mdma ecstasy pills vendor', label: 'drugs' },
  { text: 'buy xanax adderall no prescription', label: 'drugs' },
  { text: 'lean codeine promethazine bottle', label: 'drugs' },
  { text: 'lsd acid sheets for sale', label: 'drugs' },
  { text: 'research chemicals bath salts', label: 'drugs' },
  { text: 'click here buy now limited offer', label: 'spam' },
  { text: 'free money earn from home fast', label: 'spam' },
  { text: 'check out my affiliate link below', label: 'spam' },
  { text: 'subscribe to my channel telegram', label: 'spam' },
  { text: 'discount code promo sale ending', label: 'spam' },
  { text: 'dm me for link in bio', label: 'spam' },
  { text: 'sign up register now limited spots', label: 'spam' },
  { text: 'upvote this post comment below', label: 'spam' },
  { text: 'crypto giveaway send btc double', label: 'scam' },
  { text: 'verify your wallet seed phrase', label: 'scam' },
  { text: 'connect metamask claim tokens', label: 'scam' },
  { text: 'nft whitelist free mint hurry', label: 'scam' },
  { text: 'you won inheritance claim now', label: 'scam' },
  { text: 'bitcoin double investment guaranteed', label: 'scam' },
  { text: 'metamask wallet verification required', label: 'scam' },
  { text: 'airdrop claim your tokens today', label: 'scam' },
  { text: 'vaccines cause autism proof', label: 'misinformation' },
  { text: '5g towers cause cancer study', label: 'misinformation' },
  { text: 'government is lying about covid', label: 'misinformation' },
  { text: 'the truth they hide from you', label: 'misinformation' },
  { text: 'big pharma deep state control', label: 'misinformation' },
  { text: 'flat earth evidence revealed', label: 'misinformation' },
  { text: 'moon landing was fake nasa', label: 'misinformation' },
  { text: 'election results rigged stolen', label: 'misinformation' },
  { text: 'leaked footage before official release', label: 'leaked_content' },
  { text: 'early access unreleased game build', label: 'leaked_content' },
  { text: 'confidential document inside source', label: 'leaked_content' },
  { text: 'classified info embargo broken', label: 'leaked_content' },
  { text: 'datamine upcoming content season', label: 'leaked_content' },
  { text: 'pre release copy early review', label: 'leaked_content' },
  { text: 'spoiler leaked chapter summary', label: 'leaked_content' },
  { text: 'i hate this community so toxic', label: 'toxicity' },
  { text: 'everyone here is so mean rude', label: 'toxicity' },
  { text: 'disgusting behavior from mods', label: 'toxicity' },
  { text: 'offensive content should be removed', label: 'toxicity' },
  { text: 'abusive language everywhere here', label: 'toxicity' },
  { text: 'i love this game great community', label: 'clean' },
  { text: 'thanks for the help everyone', label: 'clean' },
  { text: 'does anyone know the release date', label: 'clean' },
  { text: 'here is my fan art hope you like', label: 'clean' },
  { text: 'can someone explain this bug fix', label: 'clean' },
  { text: 'just joined the subreddit hello', label: 'clean' },
  { text: 'check out this cool screenshot', label: 'clean' },
  { text: 'what time does the event start', label: 'clean' },
  { text: 'this is a great discussion topic', label: 'clean' },
  { text: 'happy birthday to the community', label: 'clean' },
];
